### PR TITLE
Removed unnecessary semi colons in source code and improved println! output

### PR DESCRIPTION
**Pull request by ghost**
1: Some unnecessary semi colons were in the python code. I have removed those.
2: Previously, calling `print("test")` would output `println!("{:?} ", "test");`. Now, it will properly output `println!("test");`. If called like this: `print(x)` or `print("test" + x)`, the correct output is still put out:
`println!("{:?} ", x);` and `println!("{:?} {:?} ", x);` respectively.

Edit:
Sorry for multiple commits. Git on VSCode was acting up.

### CODE REVIEW

**Comment by konchunas** [comment]
Hey! Thanks for your contribution, I appreciate it!
Could you please elaborate on how transpiling `print("test" + x)` to `println!("{:?} {:?} ", x);` considered proper?
I've tried to wrap my head around your code, but it doesn't make sense to me yet.
What does this check do? `values[0][0] == '"':`

**Comment by ghost** [comment]
@konchunas 
Ah, I made a typo with `println!("{:?} {:?} ", x);`. It is supposed to just be `println!("{:?} ", x);` (it is correct in the code, just not correct in my comment).
`values[0][0]` checks the first character of the 0th index of the values.
This is so if the value is "something", it can see that "something" starts with a quotation mark and know that it is a string literal. I also added the check to see if the amount of values is one.
This way, if there is only a single value in the print statement and it starts with a quote, it must be a string literal.

**Comment by konchunas** [comment]
There is an idiomatic way to check if variable is a string: `isinstance(s, str)` and you should prefer using it for both clarity and correctness.
Also from syntax perspective `print` doesn't map to `println!` as you describe. Well, technically you can do `println!` with the first argument as a string, but is proper declaration is `println!(format_string: String, args_to_format)`. While python `print` function accepts list of arguments and function detects how to handle each argument separately.
But I have to think a little bit more about this issue, thank you!

**Comment by ghost** [comment]
@konchunas 
> Also from syntax perspective `print` doesn't map to `println!` as you describe.

Can you elaborate more on this?
Calling `println!("something");` is the correct syntax for what I am referring to.
I mapped `print("something") -> println!("something")` instead of `println!("{:?}", "something")` which is the syntactically correct way to do it.
If I am missing something please let me know.

**Comment by konchunas** [comment]
Python `print` method is declared as `print(args)`
While Rust `println!` macro is declared like `println!(format, args)`
Python infers how to print the arguments automatically in runtime.
Rust needs your help to understand how to display arguments at compile time and that's why `format` variable has to be passed first before passing actual list of arguments.
While putting a string literal in format can be used for displaying it, this is not a proper thing to do. It is just a coincidence that format argument is a string, it could be anything else.
What is implemented now is a proper way of translating prints between these two languages.

**Pull request closed without merging**
